notify:
  description: Envoie un message aux panneaux LED Notifheure via MQTT
  fields:
    message:
      description: Le message \Ufffffffffficher sur le panneau LED
      example: "Prod 3.5 kW"
      required: true
    target:
      description: Liste des panneaux cibles (noms configur\Uffffffff
      example: ["salon", "cuisine"]
      required: false
    data:
      description: Options suppl\Uffffffffntaires
      required: false
      fields:
        options:
          description: Options de formatage (nzo=0;pause=1)
          example: "nzo=0;pause=1"
          required: false
